### PR TITLE
Another (maybe better) method of using prezto with zgen

### PR DESCRIPTION
**Pull request by m42e**
- Loading and creating symlink for prezto
- using preztos builtin module load function
- allow setting of prezto options

### CODE REVIEW

**Comment by N4M3Z** [comment]
Well done, this easily beats my implementation #27

**Comment by m42e** [comment]
I've also added the possibility to load a repository as prezto module. So you can add additional modules (including the functions part) loaded with prezto system, but added via zgen.

**Comment by m42e** [comment]
I will create a change request for the module feature as soon as this gets merged :)

**Comment by dan-silva** [comment]
Hmm... I found no way to set the `zstyle ':prezto:*:*' color 'yes'` option without adding a `.zpreztorc`. Shouldn't this option be available through `zgen prezto <something>`?

**Comment by m42e** [comment]
@dan-silva You are right, this was not working nicely. I improved it a bit to be more like one might expect it. You can now use ` zgen presto '*:*' color 'yes'` and it works like charm ;)

**Comment by N4M3Z** [comment]
This should be merged.

**Comment by dan-silva** [comment]
Hmm, my `zstyle` command still gives me this (using `zgen prezto '*:*' color 'yes'`):
```
[...]
color
        :prezto:module:*:* yes
[...]
```

while it should be:
```
[...]
color
        :prezto:*:* yes
[...]
```

**Comment by m42e** [comment]
Strange, It works fine for me. Can you double-check you are using the correct version?

**Comment by dan-silva** [comment]
Yup, I removed the .zgen directory and cloned again... I'll try again in a few minutes, brb.

**Comment by m42e** [comment]
Heres my zshrc snippet and the resulting .zgen/init.zsh:

```
ZGEN_PREZTO_LOAD_DEFAULT=0
source "${HOME}/.dotfiles/base/zgen/zgen.zsh"

# check if there's no init script
if ! zgen saved ; then
    echo "Creating a zgen save"


    zgen prezto
    zgen prezto prompt theme 'paradox'
    zgen prezto editor key-bindings 'vi'
    zgen prezto utility:ls color 'yes'
	zgen prezto '*:*' color 'yes'
    zgen prezto git
    zgen prezto environment
    zgen prezto terminal
    zgen prezto editor
    zgen prezto directory
    zgen prezto spectrum
    zgen prezto utility
    zgen prezto completion
    zgen prezto prompt
    zgen prezto archive
    zgen load m42e/prezto_extras 

    # plugins
    zgen load zsh-users/zsh-syntax-highlighting
    zgen load hchbaw/opp.zsh
    #zgen load djui/alias-tips

    # completions
    zgen load zsh-users/zsh-completions src
    zgen load ${HOME}/.dotfiles/common/zsh/scripts/completions 

    # save all to init script
    zgen save
fi
```
.zgen/init.zsh
```
#
# Generated by zgen.
# This file will be overwritten the next time you run zgen save

ZSH=/Users/matthias/.zgen/sorin-ionescu/prezto-master

# init prezto
zstyle ':prezto:module:prompt' theme 'paradox'
zstyle ':prezto:module:editor' key-bindings 'vi'
zstyle ':prezto:module:utility:ls' color 'yes'
zstyle ':prezto:*:*' color 'yes'

#
source "/Users/matthias/.zgen/sorin-ionescu/prezto-master/init.zsh"
source "/Users/matthias/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"
source "/Users/matthias/.zgen/hchbaw/opp.zsh-master/opp.plugin.zsh"

#
# Add our plugins and completions to fpath
#
fpath=(/Users/matthias/.zgen/sorin-ionescu/prezto-master /Users/matthias/.zgen/m42e/prezto_extras-master /Users/matthias/.zgen/zsh-users/zsh-syntax-highlighting-master /Users/matthias/.zgen/hchbaw/opp.zsh-master /Users/matthias/.zgen/zsh-users/zsh-completions-master/src /Users/matthias/.dotfiles/common/zsh/scripts/completions ${fpath})

# init prezto
pmodload 'git''environment''terminal''editor''directory''spectrum''utility''completion''prompt''archive'
```

**Comment by dan-silva** [comment]
I'm sorry... I believe I made something wrong. Just cloned your fork again and generated the init.zsh, and everything worked fine! Thank you!

Just to note... my config is in the following order, and working well:

```
[...]

  zgen prezto
  zgen prezto 'completion'
  zgen prezto 'command-not-found'
  zgen prezto 'directory'
  zgen prezto 'editor'
  zgen prezto 'environment'
  zgen prezto 'git'
  zgen prezto 'history'
  zgen prezto 'node'
  zgen prezto 'python'
  zgen prezto 'ruby'
  zgen prezto 'utility'
  zgen prezto 'syntax-highlighting'
  zgen prezto 'history-substring-search'
  zgen prezto 'prompt'

  # Config
  zgen prezto '*:*' color 'yes'
  zgen prezto 'editor' key-bindings 'vi'
  zgen prezto 'editor' dot-expansion 'yes'
  zgen prezto 'editor:info:completing' format '...'
  zgen prezto 'history-substring-search:color' found 'bg=6,fg=0,bold'
  zgen prezto 'history-substring-search:color' not-found 'bg=1,fg=0,bold'
  zgen prezto 'prompt' theme 'agnoster'
  zgen prezto 'ruby:chruby' auto-switch 'yes'
  zgen prezto 'syntax-highlighting' highlighters \
    'main' \
    'brackets' \
    'pattern' \
    'root'

[...]
```

Is there any specific reason for the need of setting the prezto options before loading the module in your README?

**Comment by m42e** [comment]
The first time when the init.zsh is generated the config is not available for prezto. In the init file it is in the correct order anyway.

**Comment by dan-silva** [comment]
Hmm... yeah, it makes sense. It is happening to me too, but I simply create another tmux pane on my setup.

**Comment by tarjoilija** [comment]
Got back from my vacation. I'll review this ASAP.

**Comment by m42e** [comment]
Welcome back. Let me rebase it onto the current master.

**Comment by N4M3Z** [comment]
Excellent!

**Pull request merged**
