### PR TITLE
Use file creation and changedate to detect change

### PR DESCRIPTION
**Pull request by m42e**
shasum is to slow, and creation and changedate seems to be exactly
enough. See #46

### CODE REVIEW

**Comment by tarjoilija** [comment]
```stat -f "%m %c"``` produces strange output for me. GNU stat differs from the mac version of stat and I think we can't use it to produce timestamp. However the REALFILE thing seems quite handy and it could be used to figure out ```ZGEN_SOURCE```.

**Comment by pearofducks** [comment]
Fixing the "strange output" is trivial:

```
`stat --version` && stat_cmd="stat -f '%m %B'" || stat_cmd="stat -c '%Y %W'"
CHANGESHA=`$stat_cmd ${REALFILE}`
echo "if [[ \"\`$stat_cmd ${REALFILE}\`\" != \"$CHANGESHA\" ]]; then" >> "${ZGEN_INIT}"
```

**Comment by m42e** [comment]
Fixed it as @pearofducks suggested.

**Comment by tarjoilija** [comment]
We got a (somewhat) working implementation merged on #60

**Pull request closed without merging**
