### PR TITLE
Added functionality to clone and load Prezto through Zgen, the function ...

### PR DESCRIPTION
**Pull request by N4M3Z**
Hello, I wrote a function to integrate Prezto framework. It is written along the lines of the oh-my-zsh function. Completion was adjusted accordingly. Also note that the $ZSH variable is now used to point to either oh-my-zsh or Prezto directory using internal function -zgen-append.

### CODE REVIEW

**Comment by tarjoilija** [comment]
Nice!

Can someone verify if it's working properly? I'm unable to test it right now.

**Comment by N4M3Z** [comment]
Testers are welcome. Please let me know of any issues.

**Comment by dan-silva** [comment]
Running `zgen prezto` worked well for me, but when I tried `zgen prezto modules/git`, it tried to clone `https://github.com/modules/git.git/` instead of just sourcing the `modules/git` module.

I could make it work with `zgen load sorin-ionescu/prezto modules/git`, but I guess that the intended behaviour was to make `zgen prezto modules/some_plugin` work just like `zgen oh-my-zsh plugins/some_plugin`.

**Comment by seletskiy** [comment]
@N4M3Z: any progress on this issue?

**Comment by N4M3Z** [comment]
Hi all, could you paste here a specific example so I can reproduce it?

**Comment by seletskiy** [comment]
BTW, I've managed to use prezto using origin version of zgen by following:

[.zshrc#L3-6](https://github.com/seletskiy/dotfiles/blob/master/.zshrc.template#L3-6):
```zsh
ln -sfT ~/.zgen/sorin-ionescu/prezto-master ~/.zprezto

source /usr/share/zsh/scripts/zgen/zgen.zsh
```
[.zshrc#L11](https://github.com/seletskiy/dotfiles/blob/master/.zshrc.template#L11):
```zsh
zgen load sorin-ionescu/prezto
```

**Comment by N4M3Z** [comment]
How do we proceed about this merge? Should I just move the `zgen-prezto` function to the new version of `zgen`?

**Comment by m42e** [comment]
You may try #40, another approach to enable Zheng for prezto

**Comment by dan-silva** [comment]
#40 was already merged, shouldn't this one be closed?

**Comment by tarjoilija** [comment]
Yes :)

**Pull request closed without merging**
