### PR TITLE
Using `touch` to create init.zsh file to avoid clobber issues.

### PR DESCRIPTION
**Pull request by N4M3Z**
Hi, I tried to address the (no)clobber problem in a more simple way. I also added another enviroment variable that points to zgen.zsh itself (I found it useful).

### CODE REVIEW

**Comment by tarjoilija** [comment]
What are the benefits of using ```touch``` instead of ```>!```? As far as I know ```NOCLOBBER``` works with the latter one.

Also hard coding zgen file name doesn't look right. Perhaps we can use ```ZGEN="${0}"``` instead.

**Comment by N4M3Z** [comment]
I believe using ```touch``` makes it easier to avoid the issue with users who have: ```unsetopt CLOBBER```.

Concerning ```zgen.zsh```, what exactly do you mean by ```ZGEN="${0}"```?

**Comment by N4M3Z** [comment]
What is the conclusion about this merge? My version of zgen already conflicts with upstream. I did this because of the way clobber interfered with the creation of `init.zsh`. I am however unable to reproduce the problem for the current version of `zgen`. 

Excerpt from zsh docs:
```
CLOBBER
Allows ‘>’ redirection to truncate existing files, and ‘>>’ to create files. Otherwise ‘>!’ or ‘>|’ must be used to truncate a file, and ‘>>!’ or ‘>>|’ to create a file.
```

**Comment by tarjoilija** [comment]
I think `>!` is a cleaner solution afterall and it seems to work on everyone. I'm closing pr because the zgen-save function got refactored.

**Pull request closed without merging**
